apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::037537801068:role/eksctl-eksctl-demo-nodegroup-ng-4-NodeInstanceRole-19L1HWGMSOESH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::037537801068:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-14T21:32:01Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1491"
  uid: d07f52d6-cee3-46c9-89c6-db008266f9c2
